// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct Test
{
    struct Test_vtable *vptr;
};

struct BS
{
    struct BS_vtable *vptr;
};

// vtables structures
struct Test_vtable
{
};

struct BS_vtable
{
    int(*b)(struct BS*, int);
};

// method declarations
int BS_b(struct BS * this, int res);

// vtables
struct Test_vtable Test_vtable_ = 
{
};

struct BS_vtable BS_vtable_ = 
{
    BS_b,
};

// methods
int BS_b(struct BS * this, int res)
{
    int * number;
    number = ((int *)(Tiger_new_array(2 * 3 * sizeof(int))));
    number[2] = 4;
    res = number[0];
    return number[2];
}

// main method
int Tiger_main()
{
    struct BS * x_0;
    System_out_println((x_0=((struct BS*)(Tiger_new(&BS_vtable_, sizeof(struct BS)))), x_0->vptr->b(x_0, 20)));
}

